# 1. build a package using mvn
# 2. upload *.jar to Artifactory
# 2. publish releases to GitHub packages

name: mvn pipeline

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu20.04

    steps:
    - uses: actions/checkout@v2
    - name: configure JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github                       #distributionManagement/repository/id
        settings-path: ${{ github.workspace }}  # path to settings.xml

    - name: Build with Maven
      run: mvn package

    - name: Publish to GH Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
